In [9]:
from functions import reterive_clean_data

In [10]:
# it s working 
df_match,df_team,df_player = reterive_clean_data('general')

/home/ali/Desktop/EuroFootballClustering/functions.py:44: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_player['potential'].fillna(df_player['potential'].mean(), inplace = True)
/home/ali/Desktop/EuroFootballClustering/functions.py:45: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_player['overall_rating'].fillna(df_player['overall_rating'].mean(), inplace = True)

# ------------------------player-------------------

In [ ]:
df_player

,id_player,player_name,birthday,height,weight,id_attribute,player_id,date,overall_rating,potential,...,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,season
0,1,Aaron Appindangoye,1992-02-29 00:00:00,182.88,187,1,505942,2016-02-18,67.0,71.0,...,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0,2015/2016
1,1,Aaron Appindangoye,1992-02-29 00:00:00,182.88,187,2,505942,2015-11-19,67.0,71.0,...,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0,2015/2016
2,1,Aaron Appindangoye,1992-02-29 00:00:00,182.88,187,3,505942,2015-09-21,62.0,66.0,...,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0,2015/2016
3,1,Aaron Appindangoye,1992-02-29 00:00:00,182.88,187,4,505942,2015-03-20,61.0,65.0,...,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0,2014/2015
4,1,Aaron Appindangoye,1992-02-29 00:00:00,182.88,187,5,505942,2007-02-22,61.0,65.0,...,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0,2006/2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,11075,Zvjezdan Misimovic,1982-06-05 00:00:00,180.34,176,183974,39902,2009-08-30,83.0,85.0,...,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0,2009/2010
183974,11075,Zvjezdan Misimovic,1982-06-05 00:00:00,180.34,176,183975,39902,2009-02-22,78.0,80.0,...,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0,2008/2009
183975,11075,Zvjezdan Misimovic,1982-06-05 00:00:00,180.34,176,183976,39902,2008-08-30,77.0,80.0,...,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0,2008/2009
183976,11075,Zvjezdan Misimovic,1982-06-05 00:00:00,180.34,176,183977,39902,2007-08-30,78.0,81.0,...,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0,2007/2008
183977,11075,Zvjezdan Misimovic,1982-06-05 00:00:00,180.34,176,183978,39902,2007-02-22,80.0,81.0,...,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0,2006/2007

# -----------------------team/match-----------------

In [12]:
df_match

,id,country_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,...,shotoff,foulcommit,card,cross,corner,possession,league_name,country_name,home_team,away_team
0,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,...,None,None,None,None,None,None,Belgium Jupiler League,Belgium,KRC Genk,Beerschot AC
1,2,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,...,None,None,None,None,None,None,Belgium Jupiler League,Belgium,SV Zulte-Waregem,Sporting Lokeren
2,3,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,...,None,None,None,None,None,None,Belgium Jupiler League,Belgium,KSV Cercle Brugge,RSC Anderlecht
3,4,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,...,None,None,None,None,None,None,Belgium Jupiler League,Belgium,KAA Gent,RAEC Mons
4,5,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,...,None,None,None,None,None,None,Belgium Jupiler League,Belgium,NaN,Standard de Liège
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,...,None,None,None,None,None,None,Switzerland Super League,Switzerland,FC St. Gallen,FC Thun
25975,25976,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,...,None,None,None,None,None,None,Switzerland Super League,Switzerland,FC Vaduz,FC Luzern
25976,25977,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,...,None,None,None,None,None,None,Switzerland Super League,Switzerland,Grasshopper Club Zürich,FC Sion
25977,25978,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,...,None,None,None,None,None,None,Switzerland Super League,Switzerland,NaN,FC Zürich
25978,25979,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,...,None,None,None,None,None,None,Switzerland Super League,Switzerland,BSC Young Boys,FC Basel

In [13]:
df_team

,id_team,team_long_name,team_short_name,id_team_attribute,team_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,49119,FC Aarau,AAR,1,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,49119,FC Aarau,AAR,2,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,49119,FC Aarau,AAR,3,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,39393,Aberdeen,ABE,4,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,39393,Aberdeen,ABE,5,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,3,SV Zulte-Waregem,ZUL,1454,10000,2011-02-22 00:00:00,52,Balanced,NaN,Little,...,53,Normal,Organised,46,Medium,48,Press,53,Normal,Cover
1454,3,SV Zulte-Waregem,ZUL,1455,10000,2012-02-22 00:00:00,54,Balanced,NaN,Little,...,50,Normal,Organised,44,Medium,55,Press,53,Normal,Cover
1455,3,SV Zulte-Waregem,ZUL,1456,10000,2013-09-20 00:00:00,54,Balanced,NaN,Little,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1456,3,SV Zulte-Waregem,ZUL,1457,10000,2014-09-19 00:00:00,54,Balanced,42.0,Normal,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1457,3,SV Zulte-Waregem,ZUL,1458,10000,2015-09-10 00:00:00,54,Balanced,42.0,Normal,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover